### ISSUE TITLE
merge的一个问题（多个tablet进行merge可能导致时序混乱）

### ISSUE THREAD

**Issue by taocp** [baidu/tera#100]
a和b进行merge，先分别执行unload
b的unload失败进而重新被load起来成为ready状态，
接着b和c被选中进行merge，分别进行unload，
之后a的unload成功，发现b仍处于unload状态（此时b的unload是为c而准备的，但a不知道，以为b还在为a而unload，因而将自己转为OnMerge状态，苦苦等待着b的unload结束开始merge） :cry: 

b和c的unload成功后merge出d来，b就从tablet界消失了，a却一直处于OnMerge状态。。。好可怜的a啊，求程序猿解救！

**Comment by taocp** [comment]
另外，ts的restart事件是不是也要注意下？

**Comment by xupeilin** [comment]
我来跟进

**Comment by xupeilin** [comment]
unload失败的原因都是超时，这个时候是不会发生一个失败的unload比一个成功的unload更早返回， 不会存在这个问题

**Comment by taocp** [comment]
当时看日志确认看到了这个问题啊。。。现场没了，原因可能分析有问题，但确认存在这么个现象。

**Comment by bluebore** [comment]
“确认存在这么个现象”
为什么还close啊？

**Comment by taocp** [comment]
其实我是为了测试`如果存在一个owner没有subscribe的issue，当它被关闭时owner是否会收到通知`。

**Comment by xupeilin** [comment]
回忆一下当时时什么场景。。是不是在并发控制的情况下才出这个问题的

**Comment by taocp** [comment]
可能是当时我搞出来的bug。。。已经没有现场了，如果复现再开这个issue吧。
