### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [baidu/tera#1052]
I guess that a different program design will be needed for your function "[SignalIntHandler](https://github.com/baidu/tera/blob/af82f3cc09d8866264751f71a3694dcab9c214f1/src/tera_main.cc#L23)".
- The variable "`g_quit`" should [use the data type "`sig_atomic_t`"](https://www.securecoding.cert.org/confluence/display/c/SIG31-C.+Do+not+access+shared+objects+in+signal+handlers) (instead of "`bool`").
- Will it be [safer](https://www.securecoding.cert.org/confluence/display/c/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers) to omit the logging call there?

**Comment by caijieming-baidu** [comment]
g_quit will eventually become true, so i think it need not to be sig_atomic_t.

**Comment by elfring** [comment]
I find this kind of feedback strange. How do you think about to check information sources for the safe data exchange with signal handlers once more?
