### ISSUE TITLE
bug of merge: one tablet may stay in OnMerge status forever

### ISSUE THREAD

**Issue by 00k** [baidu/tera#1079]
tablet A and B merge to C:
1. A and B will enter the **special** unloading process for merge
2. if tablet A unload failed, while B is still unloading, tablet A will enter the **ordinary** unloading process, and its status will be changed to **Ready**, **eventually**
3. after tablet B unload success, its status will be changed to **OnMerge**, **forever**

**Comment by caijieming-baidu** [comment]
please redirect to #954
