### ISSUE TITLE
remove cmake from build.sh

### ISSUE THREAD

**Issue by 00k** [baidu/tera#1094]
Cmake is a basic program component that every programmer should install,  just like gcc, make, python, etc.
Installation of cmake is very very slow, takes 1/2 of total build time of Tera in travis.
libreadline, libncurses, python are not installed by build.sh, cmake should also not.
How do you think of it?

**Comment by taocp** [comment]
Maybe a good idea

**Comment by caijieming-baidu** [comment]
remove from build，while we should add it to readme or somewhere.

**Comment by 00k** [comment]
@caijieming-baidu  Of course.
