### ISSUE TITLE
compile error : The bug is not reproducible, so it is likely a hardware or OS problem.

### ISSUE THREAD

**Issue by longhaidadi** [baidu/tera#1111]
g++ -DSOFA_PBRPC_ENABLE_DETAILED_LOGGING -O2         -pipe -W -Wall -fPIC -D_GNU_SOURCE -D__STDC_LIMIT_MACROS -DHAVE_SNAPPY -Isrc -I/home/lon/workspace/tera/thirdparty/boost_1_58_0 -I/home/lon/workspace/tera/thirdparty/include -I/home/lon/workspace/tera/thirdparty/include -I/include -c src/sofa/pbrpc/common.cc -o src/sofa/pbrpc/common.o
#The bug is not reproducible, so it is likely a hardware or OS problem.
make: *** [src/sofa/pbrpc/http-agent/http_agent.o] Error 1
make: *** Waiting for unfinished jobs....

my gcc : gcc (Ubuntu 4.8.4-2ubuntu1~14.04.1) 4.8.4
my os : Description:	Ubuntu 14.04.2 LTS Release:	14.04 Codename:	trusty

thanks

**Comment by 00k** [comment]
It seems like you are using **parallel** compiling. That's why the error message didn't print in the right place. Without error message, it's difficult for us to find out the reason.
As you say, it didn't reproduce, why not we see it the next time it happens.
