### ISSUE TITLE
1000 stars! Need celebrate?

### ISSUE THREAD

**Issue by 00k** [baidu/tera#1112]
<img width="195" alt="default" src="https://cloud.githubusercontent.com/assets/9716419/21039084/1d2ff92a-be16-11e6-81f7-65fe368c5094.png">

**Comment by taocp** [comment]
Mosaic for privacy! :joy:

**Comment by ddorian** [comment]
Celebrate by translating all docs/issues/code-comments/pull-requests to english!
Also fixing broken links!
