### ISSUE TITLE
tera::Table中，这两个函数作用相同吗？ virtual void Put(RowMutation* row_mutation) = 0; virtual void ApplyMutation(RowMutation* row_mu) = 0

### ISSUE THREAD

**Issue by zhenzhen01** [baidu/tera#1116]
tera::Table中，这两个函数作用相同吗？ virtual void Put(RowMutation* row_mutation) = 0; virtual void ApplyMutation(RowMutation* row_mu) = 0;

**Comment by 00k** [comment]
相同，后者是deprecated，用Put吧

**Comment by 00k** [comment]
已解决
