### ISSUE TITLE
DropTable()失败

### ISSUE THREAD

**Issue by zhenzhen01** [baidu/tera#1117]
一张已存在的表，执行：
client->DropTable(table_name,  &err_code);
显示失败信息：
[SystemError]，[table status: enable.]. table status: enable.
这是什么原因？

**Comment by taocp** [comment]
出于安全等方面的考虑（例如防止手抖误删），需要先disable再drop的。

这种管理操作，一般建议可以用 `teracli` 来做，会方便点。

```
./teracli disable <tablename>

./teracli drop <tablename>
```

**Comment by 00k** [comment]
已解决
