### ISSUE TITLE
let's make a roadmap

### ISSUE THREAD

**Issue by 00k** [baidu/tera#1121]
1. When do we release v1.0 ?
2. What should we do for v1.0 ?
3. What should we do for farther future ?

This is an open disscution. Say anything in your mind freely.
English and 中文 are both OK.

**Comment by taocp** [comment]
1. Maybe record count

**Comment by caijieming-baidu** [comment]
配套的集成测试

**Comment by caijieming-baidu** [comment]
功能上，已有的业务基本都满足了，新的业务也没有提出新的需求；感觉功能是基本完备的，大家怎么看？

**Comment by taocp** [comment]
囧，并不是吧。感觉这是典型的幸存者偏差。。。
只能说目前基本能让业务活着、跑起来了。肯定有很多需求没满足导致业务想其它办法跑起来的。还有些因为tera不满足某些特性，于是放弃使用袅 :joy:

**Comment by bluebore** [comment]
我也感觉1.0 追求的不应该是更多的功能, 而是把当前已有的功能推向市场
不过有觉得哪些功能还不足的,也可以提啊, 先发散下思维

**Comment by 00k** [comment]
对现有业务更好的支持：
1. 用户管理，权限和quota
2. scan性能（mapreduce）
3. 缩短挂机恢复时间
4. 记录级cache

对未来业务的支持：
1. 热备
2. 多级索引
3. 快照
4. 分布式事务
5. 扩数据中心备份

**Comment by caijieming-baidu** [comment]
请加上分布式测试

**Comment by bluebore** [comment]
换个思路想想,  最大集合可能很大, 最小集合可能很小, 比如如果12月31号前必须发布1.0, 我们还有哪些必须做的

**Comment by yvxiang** [comment]
和其它系统的兼容接口？

**Comment by 00k** [comment]
看1.0怎么定义了。如果是为了市场推广，可能bug都不需要修了，把文档弄好就够了。

**Comment by caijieming-baidu** [comment]
搞个预售版的1.0，是现有功能的一次完备的总结；看看反应，再考虑是否搞个最终版的1.0

**Comment by bluebore** [comment]
1.0本来就不带有终版的意思吧, 还可以有1.1, 2.0, 3.0啊

**Comment by 00k** [comment]
第3个问题大家也积极讨论吧，目前还没有
对于第2个问题，是不是要根据第1个问题的答案来定？或者反过来？

**Comment by bluebore** [comment]
对于第一个问题，我建议tera赶在bfs前面，春节前吧。
关于第三个问题，未来可以有两条路并行， 更多的功能（比如高可用，OLAP支持），更大范围的推广。

**Comment by caijieming-baidu** [comment]
搞推广的话，怎么提升我们的技术能力呀；离销售越来越近了，有木有

**Comment by 00k** [comment]
1. 明年3月底前
2. 上面说的“对现有业务更好的支持”里面的
3. 上面说的“对未来业务的支持”里面的
上面是原答案。但bluecore说春节前发布，我觉得也没问题。

**Comment by bluebore** [comment]
推广开的话，就有机会解除更多更广的技术， 才能提升啊， 如果项目进入维护阶段，代码不再升级， 才没法提升技术能力了呢。产销结合~
