### ISSUE TITLE
从tera::Table::Get(...)到rpc接口的关键函数调用序列可以列举一下么？

### ISSUE THREAD

**Issue by zhenzhen01** [baidu/tera#1124]
如题。

**Comment by 00k** [comment]
1. Get的各种变形最终都会调用DistributeReaders。DistributeReaders是读操作的总入口，它的功能是对每个RowReader的rowkey查一次meta，根据rowkey所在的server进行分类。每个server会有一个RowReader集合，属于某个server的RowReader会被加到相应的集合中。分类结束后，DistributeReaders会对每个server的RowReader集合分别调用PackReaders函数。
1. PackReaders的功能是打包RowReader。它会将RowReader集合与之前尚未发送的RowReader集合进行合并，并判断合并后的集合大小是否大于打包阈值，是的话调用CommitReadersById；否的话设置一个最大等待时间并直接返回，当这部分集合会与后续的集合合并，或者在最大等待时间到达后，被调用CommitReadersById。
1. CommitReadersById会检查每个RowReader是否已经超过用户设置的超时时间，是的话就不去处理，否则会把它再加入一个待发送集合中，最后调用CommitReaders。
1. CommitReaders将RowReader集合序列化为一个request，并调用RPC的ReadTablet接口。
