### ISSUE TITLE
./build.sh  在编译leveldb时失败

### ISSUE THREAD

**Issue by syeerzy** [baidu/tera#1135]
ar: creating libleveldb.a
g++ db/db...........[省略各个文件名]........  -lcrypto -ldl -lsnappy
/bin/ld: cannot find -lcrypto
collect2: error: ld returned 1 exit status
make[1]: *** [db_bench] Error 1
make[1]: Leaving directory '........./tera/src/leveldb'
make: *** [src/leveldb/libleveldb.a] Error 2
make: *** Waiting for unfinished jobs . . . .

系统为CentOS7

**Comment by 00k** [comment]
缺少libcrypto.so
执行 yum install openssl-devel 安装即可
