### ISSUE TITLE
more effective find split key

### ISSUE THREAD

**Issue by 00k** [baidu/tera#1137]
Because calculating a split key will not help to find a real middle key which is able to split the data into two identical parts, I think up a new idea to replace it:

S1 = total size of level 0 files
S2 = total size of other levels files
```
if (S1 > S2)
  split key = mid key of largest sst file of level0
else
  split key = current Version::FindSplitKey()
fi
if split key == start key or split key == end key
  abort split
fi
```

It works even there is only level 0 files.

**Comment by 00k** [comment]
edit:
```
if (S1 > S2)
  if (file num < 3)
    mid key of newest sst file of level 0
  else
    mid of mid keys of newest 3 sst files of level 0
  fi
fi
```

**Comment by taocp** [comment]
seems good!

**Comment by xupeilin** [comment]
I think tablet should support split even none sst files.
For new comers, they can try split/merge/move in onebox and empty tables.

**Comment by 00k** [comment]
Good point. We can add a command like "./teracli force split t1/tablet001" in teracli for new comers to experience. But for product use, splitting empty tablet is useless.
