### ISSUE TITLE
sdk settings on timeout and retry

### ISSUE THREAD

**Issue by cjj168pc** [baidu/tera#1138]
How to set timeout and retry times in sdk?
I saw various variables about timeout in source code, like `tera_sdk_timeout`, `tera_sdk_delay_send_internal`, `tera_sdk_retry_times`, `tera_sdk_retry_period`.
What does these variables mean?

**Comment by 00k** [comment]
Use RowMutation::SetTimeOut(int64_t timeout_ms)  to set timeout for a single write request.
Use RowReader::SetTimeOut(int64_t timeout_ms)  to set timeout for a single read request.
The variables you mentioned are for internal usage. You could just disregard them.
