### ISSUE TITLE
cache env support dfs

### ISSUE THREAD

**Issue by 00k** [baidu/tera#1180]
In the past, base env maybe be dfs or local, but cache env has to be local.
Now cache env can also be dfs, too.

**Comment by xupeilin** [comment]
这个功能建议放到新的大版本中，对dfs有更高的要求，可以考虑做成bfs联合发布
否则对其它dfs没有意义，甚至有反作用
这个功能需要把tera的架构图都改了

**Comment by 00k** [comment]
是的，这个功能是向前兼容的，不影响原来的cache实现，对于使用其他dfs的用户，还是用原先的用法。
另外，它也不只是给bfs定制的，如果有别的dfs支持单副本、性能和稳定性足够高，也是可以作为cache层的。所以可以算是tera的一个通用功能，是对现有cache的补充。

**Comment by 00k** [comment]
没想太清楚，以后再说
