### ISSUE TITLE
sync manifest超时异常处理有问题

### ISSUE THREAD

**Issue by taocp** [baidu/tera#1197]
细节 todo

**Comment by bluebore** [comment]
这个我想了下, 可以增加一个切manifest的操作
如果manifest的sync失败了, 就切个新的

**Comment by taocp** [comment]
@caijieming-baidu  在做，也是这个想法。

**Comment by caijieming-baidu** [comment]
问题场景：manifest写或sync超时返回，数据可能最终已经进入manifest，导致version set与manifest视图不一致，ts宕机重启之后，导致数据丢失；
