### ISSUE TITLE
尝试使用tera过程中遇到的问题，请赐教

### ISSUE THREAD

**Issue by ontologyzsy** [baidu/tera#126]
几个概念问题：
1、api描述中，LG，CF，都是什么概念？划分原则是什么样的？
2、mutation Reader 的读写接口中 的参数qualifier是什么？
3、scan接口描述中
在设置区间返回后，做了下面两个add
desc->AddColumnFamily("family21");
desc->AddColumn("family22", "qualifier22");
是指定scan的列么？
如果不指定，可以scan整行么？
scan多列之后，如何从result_stream中读某列数据。
请在api描述中解释一下，非常感谢。

**Comment by bluebore** [comment]
弄个faq解决。
