### ISSUE TITLE
最新版master分支编译失败

### ISSUE THREAD

**Issue by skillness** [baidu/tera#1287]
![default](https://user-images.githubusercontent.com/8231208/26881009-c3dc916c-4bc8-11e7-8a64-7729d9c07111.PNG)

文字编译信息：
In file included from src/master/tablet_manager.cc:13:0:
/home/tl/tera-master/thirdparty/include/glog/logging.h: In instantiation of ‘std::__cxx11::string* google::Check_GTImpl(const T1&, const T2&, const char*) [with T1 = unsigned int; T2 = int; std::__cxx11::string = std::__cxx11::basic_string<char>]’:
src/master/tablet_manager.cc:1026:13:   required from here
/home/tl/tera-master/thirdparty/include/glog/logging.h:700:32: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
 DEFINE_CHECK_OP_IMPL(Check_GT, > )
                                ^
/home/tl/tera-master/thirdparty/include/glog/logging.h:133:53: note: in definition of macro ‘GOOGLE_PREDICT_TRUE’
 #define GOOGLE_PREDICT_TRUE(x) (__builtin_expect(!!(x), 1))
                                                     ^
/home/tl/tera-master/thirdparty/include/glog/logging.h:700:1: note: in expansion of macro ‘DEFINE_CHECK_OP_IMPL’
 DEFINE_CHECK_OP_IMPL(Check_GT, > )
 ^

似乎是在src/master/tablet_manager.cc中1026行：

```c++
 CHECK_GT(file_info.ref, 0);
```

调用 CHECK_GT 时，由于 file_info.ref 的类型是`uint32_t`，字面常量0的类型是int，对它俩进行比较时会报warning，由于编译时开启了-Werror，因此编译失败。

不知是这个原因吗？

编译是通过直接运行build.sh进行的

**Comment by 00k** [comment]
是这个原因
顺便问下你的编译器是什么版本？travis是4.8编译能通过

**Comment by skillness** [comment]
恩，我用的是 5.4.0
