### ISSUE TITLE
Flash cache垃圾收集会清理正在使用的sst文件

### ISSUE THREAD

**Issue by bluebore** [baidu/tera#130]
复现方式：一个ts，一个tablet，连续写几小时，leveldb日志里就会出现copy to local

**Comment by taocp** [comment]
可以把tera.flag的日志level设置得高一点，例如
```--v=16```

这样，GC日志会比较详细，特别是删掉的每个SST都会有记录。便于排查。

**Comment by lylei** [comment]
#301
