### ISSUE TITLE
内存泄漏问题

### ISSUE THREAD

**Issue by 360CodeSafe** [baidu/tera#1326]
/src/tera_c.cc 448行

445行： tera_result_stream_t* result = new tera_result_stream_t;  分配内存
在448行return，且没有对分配内存进行释放

**Comment by DatongLi** [comment]
感谢提醒，这个问题会在下个版本update修复。

**Comment by imfht** [comment]
已经将近一年没有更新了，请问这个 repo还在维护吗？

**Comment by DatongLi** [comment]
新版本已更新
