### ISSUE TITLE
Load过程中recover失败会delete dbtable，触发shutdown，有时候死锁，有时候core

### ISSUE THREAD

**Issue by bluebore** [baidu/tera#154]
shutdown1过程中，拿不到某个锁，DBTable或是DBImpl，导致夯住。
另一种情况core
0  0x0000000000956232 in leveldb::VersionSet::LastSequence (this=0x2bf7a420105ff) at ./db/version_set.h:214
1  0x00000000009a4c11 in leveldb::DBImpl::GetLastVerSequence (this=0x7f8faabdf600) at db/db_impl.cc:1678
2  0x0000000000942de5 in leveldb::DBTable::GarbageClean (this=0x7f8e87bcff50) at db/db_table.cc:1112
3  0x000000000093c65a in leveldb::DBTable::Shutdown1 (this=0x7f8e87bcff50) at db/db_table.cc:135
#4  0x000000000093d1dd in ~DBTable (this=0x7f8e87bcff50) at db/db_table.cc:183
5  0x0000000000939c9d in leveldb::DB::Open (options=@0x7f8ebcc38ec0, dbname=@0x7f8ebcc38e88, dbptr=0x7f8ebcc38fd8) at db/db.cc:56
6  0x00000000007f78c8 in tera::io::TabletIO::Load (this=0x7f8ebcc38e30, schema=@0x7f8fba285a30, key_start=@0x7f8f571474c0, key_en

**Comment by 00k** [comment]
fix
