### ISSUE TITLE
多线程，跑异步接口，大多数情况下会崩溃

### ISSUE THREAD

**Issue by appleprince88** [baidu/tera#244]
如题。请问这是什么原因？

**Comment by fxsjy** [comment]
@appleprince88 , 是客户端崩溃还是tera集群。  目前tera的sdk流控还不健全，建议在异步环境下，应用层做好流控。 也就是说，应用层发送出去的请求数 减去 收到回调的数， 这个差不能太大。

**Comment by appleprince88** [comment]
是客户端崩溃。我会在收到所有异步回调才会退出程序，我是在回调接口用采用一个全局变量并加锁来计数的，只有计数达到请求的数量，才会退出

**Comment by fxsjy** [comment]
@appleprince88 ，能贴一下core的堆栈么？

**Comment by appleprince88** [comment]
Loaded symbols for /home/root/hadoop_client_yangquan/java6/jre/lib/amd64/libnio.so
Reading symbols from /home/root/hadoop_client_yangquan/hadoop/lib/native/Linux-amd64-64/libhadoop.so...done.
Loaded symbols for /home/root/hadoop_client_yangquan/hadoop/lib/native/Linux-amd64-64/libhadoop.so
#0  0x000000302af2e2ed in raise () from /lib64/tls/libc.so.6
(gdb) bt
#0  0x000000302af2e2ed in raise () from /lib64/tls/libc.so.6
#1  0x000000302af2fa3e in abort () from /lib64/tls/libc.so.6
#2  0x00007f353adb93f7 in os::abort () from /home/root/hadoop_client_yangquan/hadoop/../java6/jre/lib/amd64/server/libjvm.so
#3  0x00007f353af17bad in VMError::report_and_die () from /home/root/hadoop_client_yangquan/hadoop/../java6/jre/lib/amd64/server/libjvm.so
#4  0x00007f353adbe70c in JVM_handle_linux_signal () from /home/root/hadoop_client_yangquan/hadoop/../java6/jre/lib/amd64/server/libjvm.so
#5  0x00007f353adbb55e in signalHandler () from /home/root/hadoop_client_yangquan/hadoop/../java6/jre/lib/amd64/server/libjvm.so
#6  <signal handler called>
#7  0x00007f353a52f6a1 in boost::asio::detail::reactive_socket_connect_op<boost::_bi::bind_t<void, boost::_mfi::mf1<void, sofa::pbrpc::RpcByteStream, boost::system::error_code const&>, boost::_bi::list2<boost::_bi::value<sofa::pbrpc::shared_ptr<sofa::pbrpc::RpcByteStream> >, boost::arg<1> (*)()> > >::do_complete () at /usr/lib/gcc/x86_64-redhat-linux/3.4.5/../../../../include/c++/3.4.5/bits/basic_string.tcc:243
#8  0x00007f353a5109a2 in boost::asio::detail::epoll_reactor::descriptor_state::do_complete ()
    at /usr/lib/gcc/x86_64-redhat-linux/3.4.5/../../../../include/c++/3.4.5/bits/basic_string.tcc:243
#9  0x00007f353a517913 in sofa::pbrpc::ThreadGroupImpl::thread_run ()
    at /usr/lib/gcc/x86_64-redhat-linux/3.4.5/../../../../include/c++/3.4.5/bits/basic_string.tcc:243
#10 0x000000302b80610a in start_thread () from /lib64/tls/libpthread.so.0
#11 0x000000302afc6003 in clone () from /lib64/tls/libc.so.6
#12 0x0000000000000000 in ?? ()

**Comment by appleprince88** [comment]
这个问题好像是我搞错了，我现在没出现这个问题
