### ISSUE TITLE
多进程调用客户端接口，为什么在子进程中不能往下运行，会在打开table的时候挂起信号量，而在父进程中完全没有问题。

### ISSUE THREAD

**Issue by appleprince88** [baidu/tera#245]

**Comment by xupeilin** [comment]
能仔细描述下用法和现象吗

**Comment by appleprince88** [comment]
就是在子进程中调用tera的接口，会出现如题中的问题，我举个例子吧，代码如下：
<pre><code>
#include <unistd.h>
#include <sys/types.h>
#include <iostream>
#include <stdlib.h>
#include <stdio.h>
#include <sys/wait.h>

#include "tera.h"

void fun() { 
    tera::ErrorCode error_code;
    tera::Client* client = tera::Client::NewClient("./tera.flag", &error_code);
    tera::Table* table = client->OpenTable("tera_testxxx", &error_code);
    if (table == NULL) { 
        printf("Open talbe fail:%s \n", strerr(error_code));
    }
    std::string key = "1343423432423";
    tera::RowMutation* mutation = table->NewRowMutation(key);
    mutation->Put("1","1","value1");
    table->ApplyMutation(mutation);
    std::string value;
    table->Get(key, "1", "1", &value, &error_code);
    std::cout << value << std::endl;
    delete table;
    delete client; 
    
}

int main() {
    pid_t pid;
    pid = fork(); 
    if (pid > 0) {
        pid_t child_pid;
        int stat_val;
        child_pid = wait(&stat_val);
        printf("after wait child\n");
    }else if (pid == 0) { 
        printf("this is child\n");
        fun();  
    }else { 
        printf("fork error\n");
    }
    return 0;
}
</code></pre>


在fun函数的第三行也就是，打开table，会挂起信号量，gdb查看如下：
Reading symbols from /usr/lib64/libk5crypto.so.3...done.
Loaded symbols for /usr/lib64/libk5crypto.so.3
Reading symbols from /lib64/libresolv.so.2...done.
Loaded symbols for /lib64/libresolv.so.2
Reading symbols from /lib64/libnss_files.so.2...done.
Loaded symbols for /lib64/libnss_files.so.2
Reading symbols from /lib64/libnss_dns.so.2...done.
Loaded symbols for /lib64/libnss_dns.so.2
0x000000302b8089aa in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/tls/libpthread.so.0
(gdb) bt
#0  0x000000302b8089aa in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/tls/libpthread.so.0
#1  0x00007faa61ba4de3 in common::CondVar::Wait (this=0xd4b478, msg=0x0) at ./src/common/mutex.h:127
#2  0x00007faa61bd4dc2 in tera::TableImpl::UpdateTableMeta (this=0xd4b200, err=0x7fff30a96200) at src/sdk/table_impl.cc:1840
#3  0x00007faa61bc9cf1 in tera::TableImpl::OpenInternal (this=0xd4b200, err=0x7fff30a96200) at src/sdk/table_impl.cc:412
#4  0x00007faa61ba0639 in tera::ClientImpl::OpenTable (this=0xd82000, table_name=@0x7fff30a961d0, options=@0x7fff30a96127, err=0x7fff30a96200) at src/sdk/client_impl.cc:278
#5  0x00007faa61ba04b9 in tera::ClientImpl::OpenTable (this=0xd82000, table_name=@0x7fff30a961d0, err=0x7fff30a96200) at src/sdk/client_impl.cc:262
#6  0x00000000004011bd in fun () at mulpro.cpp:13
#7  0x000000000040172f in main () at mulpro.cpp:39

**Comment by 00k** [comment]
应该跟子进程无关吧，父进程不也是shell的子进程？

**Comment by appleprince88** [comment]
那这个是什么原因导致的呢？
