### ISSUE TITLE
客户端show出的size不准

### ISSUE THREAD

**Issue by bluebore** [baidu/tera#261]
没有计算level0的大小，导致show出来的和实际值差距非常大。
可以考虑计算level0的大小，也计算memtable的大小。
或者给出两个值：预估的数据量大小&DFS空间占用大小。
需要解决的问题
1. 什么时候开始出问题的
2. 怎么实现精确统计

**Comment by xupeilin** [comment]
改进的实现中，分为两种size: 
1. level>=1的sst文件大小，只对split有用，做为一种特殊的内部size_for_split使用，对外不可见
2. mem + imm + sst size,用户真实数据占的总存储，展示到客户端

**Comment by xupeilin** [comment]
存在由压缩、多列放大、删除标记、未compact无用数据等造成的数据量误差
