### ISSUE TITLE
支持表格rename

### ISSUE THREAD

**Issue by fxsjy** [baidu/tera#282]
1) 用法: teracli rename table_A table_B
2) 实现：在TableSchema中加入了alias属性，面向用户的不再是表格的name而是alias。
    也就是说，table_A是个alias, master和ts拿到的table_name是table_A@20150901121300，DFS上的文件夹的名字也是table_A@20150901121300。rename为table_B，只不过是把alias属性更改了
3）兼容性：对于以前已经建立好的表格: 老sdk<->新master或者新sdk<->老master都是兼容的。对于升级以后再建立的表格，老SDK不能使用alias的表名，只能用底层的表名。
4）rename的过程中不需要disable,enable，是一个瞬间的操作，只影响meta表和master的一些内存结构。

**Comment by fxsjy** [comment]
```
[./bin]$ ./teracli create test_A{lg0{cf0}}

  test_A <splitsize=4500> {
      lg0 <storage=disk> {
          cf0,
      },
  }

[./bin]$ ./teracli put test_A key1 cf0: value1
[./bin]$ ./teracli put test_A key2 cf0: value2
[./bin]$ ./teracli rename test_A test_B
rename OK: test_A -> test_B
[./bin]$ ./teracli put test_B key3 cf0: value3
[./bin]$ ./teracli scan test_B '' ''
key1:cf0::1441086587463156:value1
key2:cf0::1441086596026713:value2
key3:cf0::1441086611061501:value3
```

**Comment by xupeilin** [comment]
#283
