### ISSUE TITLE
teracli的showschema命令支持自动化

### ISSUE THREAD

**Issue by taocp** [baidu/tera#294]
我发现用户有一个习惯，喜欢把某个table的schema存入文件，下次用`./teracli createbyfile`来建表。
当前`showschmea`出来的内容格式上有点小不足，需要手动copy再复制到文件，直接重定向到文件是不work的，这样对自动化的支持不太友好。（具体原因见代码diff）

现在支持`./teracli showschema test_table > test_table_schema`，下次建表时`./teracli createbyfile  test_table_schema`就好，当然，表重名的问题交给用户解决。

**Comment by bluebore** [comment]
这个功能很不错，“代码diff”在哪？

**Comment by taocp** [comment]
@bluebore  不好意思啊，电脑出了点故障，访问github有点障碍，才看到消息。代码容我稍候再提pull request.
