### ISSUE TITLE
Env_dfs Rename非原子操作，DFS异常时，可能导致数据损坏

### ISSUE THREAD

**Issue by xupeilin** [baidu/tera#314]
解决方案，将DeleteFile从Rename中去除，如果DFS不支持覆盖Rename，将DeleteFile实现在DFS Wrapper中

**Comment by bluebore** [comment]
哪些DFS不支持覆盖rename这个明确么，如果明确，需要把对应dfswrapper也修改了，否则可能几个月后才被用户报出来不能用了。

**Comment by xupeilin** [comment]
HDFS（1.x&2.x）不支持覆盖rename，不能保证rename原子性
已将deleteFile添加至HDFSWrapper中
