### ISSUE TITLE
多版本scan最新版本，切换buffer时会扫出重复数据

### ISSUE THREAD

**Issue by lylei** [baidu/tera#356]
例如，`maxversions=2`，切换buffer前最后一条数据为`key:cf0:q0:10`，下一次scan发起时会以`key:cf0:q0x1:10`为起始key，第一条有效数据为`key:cf0:q0:9`，这一条数据会被误当做最新版本返回给用户。

**Comment by lylei** [comment]
一个诡异的bug。。。
schema的axversions=1，写数据，建快照，scanallv，会出和上面一样的现象。

经一系列猜测。。感觉是DefaultCompactStrategy的成员变量没有初始化导致的。所以也许和table schema之类的木有关系。

**Comment by bluebore** [comment]
果断blame
