### ISSUE TITLE
TS拒绝响应kick信号时，master对这个ts无可奈何

### ISSUE THREAD

**Issue by xupeilin** [baidu/tera#361]
现象：某台ts能和zk保持连接不断（节点在zk/ts下一直存在），不能响应任何服务请求（Query/Read等等），master会标记kick，ts无法响应

此时master不知道如何处理了，上面已经load的tablet也无法迁移，无法提供服务

暂时处理办法：手动把zk/ts上的对应结点删了

**Comment by 00k** [comment]
长期未复现，暂时关闭
