### ISSUE TITLE
putttl 功能无效

### ISSUE THREAD

**Issue by MichelleZ** [baidu/tera#370]
step1：create table
step2：通过putttl来向table中添加数据，ttl为2s
step3：get数据，得到value
step4：经过2s之后，get仍然有值

**Comment by fxsjy** [comment]
@MichelleZ ， 这个功能只在kv表里面有。

**Comment by MichelleZ** [comment]
@fxsjy 就是kv模式的，但还是不起作用的

**Comment by lylei** [comment]
建表schema需指明需要ttl
