### ISSUE TITLE
ClientImpl统一调度meta(包括本地cookie)

### ISSUE THREAD

**Issue by xupeilin** [baidu/tera#398]
当前是单个TableImpl负责自己的meta更新等，如果一个Client中open了很多个TableImpl（rtg中每个Client open TableImpl 500次）会对zk、meta等造成额外的压力，没有必要
一个Client统一调度Meta，TableImpl有需要是，调用Client的更新接口

**Comment by 00k** [comment]
将meta以及相关的数据结构放到client中，更新过程还是由tableimpl去执行，这样比较简单
补充一个额外的问题：同一table被多次open是否应该返回同一个tableImpl指针？

**Comment by xupeilin** [comment]
现在一个TableImpl只能支持一路scan,一个Client并发scan多路的情况下，现在还支持不了

**Comment by 00k** [comment]
tableimpl可以多路scan，靠flag控制的。当面聊

**Comment by lylei** [comment]
实现太复杂
