### ISSUE TITLE
Manifest在文件系统慢时，会被误删

### ISSUE THREAD

**Issue by xupeilin** [baidu/tera#417]
manifest_file_number_在leveldb中是不发生变化的，但是tera中加入了强制切换
而删除Manifest文件依赖此变量值，此值变大后会将正在生效的manifest文件删除

**Comment by bluebore** [comment]
这个值为什么会变大

**Comment by xupeilin** [comment]
![manifest-error](https://cloud.githubusercontent.com/assets/11419707/10683292/fd7dc3a2-7972-11e5-8397-02c3ed89d7f4.png)

**Comment by lylei** [comment]
#412
