### ISSUE TITLE
关于sdk的使用问题

### ISSUE THREAD

**Issue by blackfox1983** [baidu/tera#418]
1、sdk中有tera.h，有tera_easy.h……这几个不同的头文件分别有什么用？
2、尤其是tera.h中，类很多，每个类做什么用，怎么用，有没有注意的地方？

**Comment by lylei** [comment]
#272 @bluebore 正在着手整理一份sdk文档

**Comment by blackfox1983** [comment]
大概什么时候会出炉？

**Comment by 00k** [comment]
see: https://github.com/baidu/tera/blob/master/doc/sdk_dev_guide.md
