### ISSUE TITLE
leveldb中增加一个全局default logger

### ISSUE THREAD

**Issue by xupeilin** [baidu/tera#419]
经过和 @00k 讨论
当前logger的指针是放在option里的，我们只能在有option的地方使用（db_impl, version_set等少数几个地方）
但是比如env_xxx/filename等很多地方是打不了leveldb.log的，只能打到stderr里
log分散在两个文件里追查很不方便

在env.h的logger定义处增加一个默认的全局logger，想打日志时可以直接打到leveldb.log中
不用局限在可以使用option的地方

**Comment by taocp** [comment]
非常赞同！
