### ISSUE TITLE
SDK去掉GLOG依赖

### ISSUE THREAD

**Issue by xupeilin** [baidu/tera#443]
GLOG与用户的不兼容无法解决，只能考虑去掉依赖
SDK日志不多，绝大多数为异常日志，打到stderr
其它性能等日志，配置为一个日志文件，用户可配置为关闭

**Comment by taocp** [comment]
我看glog的configure文件，是有一个选项的:`--enable-namespace`，但指定后有一些编译上的问题。。。

**Comment by 00k** [comment]
用comlog和glog的用户都有，没听说不兼容啊

**Comment by lylei** [comment]
用户不需要了
