### ISSUE TITLE
tera.sdk库会打印日志但是不会清空

### ISSUE THREAD

**Issue by blackfox1983** [baidu/tera#490]
打印的日志感觉是glog打印的格式。
但是打印了日志后一直是增加，不会自动清空。
这个不太符合公司的运维规范。这块帮看下，比如我们就需要保留若干天的日志。

**Comment by blackfox1983** [comment]
我们也不关注这个日志。我理解主要是tera维护的同学去看的。
这个时候，tera自身保存一个周期即可。

**Comment by lylei** [comment]
#508
