### ISSUE TITLE
sdk代码没注释的坑。

### ISSUE THREAD

**Issue by blackfox1983** [baidu/tera#494]
错误码有两个字符串接口：
1、GetReason()
2、strerror

这两个什么注释都没有，也没说明。完全是在来回的踩坑、重编译、测试、再踩坑的循环中。

写代码不写注释，有些耍流氓啊。

**Comment by lylei** [comment]
如果想要详细错误信息，建议使用GetReason()。后续会继续针对这个问题进行优化。

**Comment by 00k** [comment]
done
