### ISSUE TITLE
未定义行为规范化

### ISSUE THREAD

**Issue by 00k** [baidu/tera#513]
- [ ] 用户时间戳

退化为单纯的版本id，不对时间合法性做检查
- [ ] 删除最新版本

不应支持非幂等写操作，因此不支持删最新版本，但应支持删指定范围内的版本
- [ ] 删表再建表，rename

表名不变但表本身发生切换后，用户的读写操作应该全部失败
- [ ] disable同步返回

从方便用户的角度考虑，同步返回更好，但若发生超时，用户有责任自行重试
- [ ] drop前是否需要disable

从用户角度考虑，不需要
- [ ] meta表和内存不一致

内存需要增加操作的中间状态(ing)，保证和meta表一致
- [ ] 写不存在列

该row的写操作应该全部失败

**Comment by lylei** [comment]
删表建表：有用户正在使用该表的情况是否可以删表，或者报warning之类的？

**Comment by 00k** [comment]
不允许删有两个缺点，对用户来说需要先停服务才能删表，不方便；对实现来说分布式引用计数比较复杂
