### ISSUE TITLE
tabletnode应该支持在不停服的情况下更新一些配置选项

### ISSUE THREAD

**Issue by taocp** [baidu/tera#517]
类似配置选项的热更新，不然更新一次配置就要重启很影响可用性。

**Comment by bluebore** [comment]
这个sofa-pbrpc本来是支持的，gflags本身是全局变量，也非常好更新。
搞起吧~

**Comment by taocp** [comment]
1. 依据现有代码的逻辑，不是所有的 flag 都支持运行时更新的，所以不能简单的用 gflags 的接口来更新所有 flag. 
2. 用户通过teracli把需要更新的flag及其值发送给ts，ts通过 case 语句找到需要更新的 flag ，每支持一个flag的更新，就需要对应修改一点代码。（暂时没想到更便捷的办法）

例如：
```
./teracli ts config realod <flag_name> <value> // 通知所有ts重置flag值，teracli带上一个hash值，ts更新成功后会在内存中保存该值
./teracli ts config list                                          // 查看所有ts上次重置后hash，以便确认每个ts都更新成功
```

这个思路咋样？
