### ISSUE TITLE
Tera数据模型的限制 的设计

### ISSUE THREAD

**Issue by taocp** [baidu/tera#518]
Tera数据模型的限制
design code
- [x]  rowkey：大小 [0, 64KB)，任意二进制串 // 现有代码

- [x]  column family：大小 [0,  64KB)，cf名本身是可打印字符串，不限制数量

- [x]  qualifier：大小 [0, 64KB)，任意二进制串 // 现有代码

- [x] value：大小 [0, 32MB) // 还和pb限制有关，不然需要大量修改现有代码绕过pb限制

- [x]  cell的版本数，不限制数量

- [x] table name：首字符为字母（大小写均可），有效字符包括大小写的英文字母(a-zA-Z)、数字(0-9)、下划线(`_`)、连字符(`-`)、点(`.`)。
1 <= 有效长度 <= 128.

参考资料：

[cloud bigtable](https://cloud.google.com/bigtable/docs/schema-design)
[file_systems#Limits](https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits)

**Comment by lylei** [comment]
cell版本数限制：依赖于大行读能否解决
