### ISSUE TITLE
文件系统容错相关逻辑用flag控制

### ISSUE THREAD

**Issue by bluebore** [baidu/tera#545]
现在tera代码里加了很多文件系统出错自动处理逻辑，如果文件系统部分异常时，上层发现不了，但导致了部分数据丢失或出错，tera的数据一致性就全完了。
所以需要添加个是否忽略文件系统错误的flag，如果不忽略，应该视每个文件系统错误为重大异常，丢弃或者停止整个tablet。

**Comment by 00k** [comment]
see #1028
