### ISSUE TITLE
文件系统异常导致Kick

### ISSUE THREAD

**Issue by bluebore** [baidu/tera#549]
文件系统异常时，不应该引发kick导致雪崩

**Comment by xupeilin** [comment]
没有雪崩，只有少量ts被kick

**Comment by bluebore** [comment]
我这崩了，kick进safemode了

**Comment by bluebore** [comment]
一点文件系统异常，就会有ts被kick，你们都没遇到这个问题
@xupeilin

**Comment by xupeilin** [comment]
ts query 处理和load tablet是同一个线程池处理的
如果load的并发数>=线程池大小，此时文件系统操作又堵住就会出现query无法响应，被kick
解决方法：加大ctrl线程池大小或降低load tablet的并发数
