### ISSUE TITLE
99.9999%分裂成功的findsplitkey， 导致start key与split key一样的bug

### ISSUE THREAD

**Issue by caijieming-baidu** [baidu/tera#552]
I1208 00:24:46.110282 16797 remote_tabletnode.cc:370] accept RPC (SplitTablet) id: 285572
I1208 00:24:46.110452 16797 tablet_io.cc:416] start: [bc], end: [], split: [bc]
I1208 00:24:46.110487 16797 tabletnode_impl.cc:742] split tablet: ktrace#trace#service_name@20151207153656/tablet00000002 [bc, ], split key: bc
I1208 00:24:46.110492 16797 tablet_io.cc:294] [Unload] start shutdown1 /disk/tera/trace-sys/ktrace#trace#service_name@20151207153656/tablet00000002

**Comment by bluebore** [comment]
你不用睡觉的么，大半夜提bug。。。

**Comment by 00k** [comment]
额，你俩。。。
