### ISSUE TITLE
flash表读不命中时，触发copy to local，随机读场景，读时延比较大

### ISSUE THREAD

**Issue by caijieming-baidu** [baidu/tera#556]
随机读触发copy to local，70M数据耗时3s+；随机读一小部分数据，且额外产生大量数据拷贝，没有任何收益；

**Comment by bluebore** [comment]
这个有什么解决思路么？

**Comment by caijieming-baidu** [comment]
随机读场景适合用record cache，不适合用block cache

**Comment by bluebore** [comment]
你再想想吧，我觉得顺序读也不怎么适合blockcache。。。
