### ISSUE TITLE
sdk目录里RowReaderImpl和RowMutationImpl类的构造函数的table参数是否是多余

### ISSUE THREAD

**Issue by stevenswong** [baidu/tera#656]
RowReaderImpl(Table* table, const std::string& row_key);

RowMutationImpl(TableImpl* table, const std::string& row_key);

请问这两个函数的第一个参数是多余的?因为源码里没有用到。

**Comment by lylei** [comment]
保留接口 以备将来使用

**Comment by lylei** [comment]
保留接口 以备将来使用

**Comment by lylei** [comment]
保留接口 以备将来使用

**Comment by lylei** [comment]
保留接口 以备将来使用
