### ISSUE TITLE
启动脚本环境配置问题导致ts退出

### ISSUE THREAD

**Issue by szxw** [baidu/tera#665]
galaxy下启动，
$ulimit -n
10240
leveldb.log打印日志
2015/12/31-16:01:47.616966 897 [env_flash] Open local flash file for write fail: /*****/00001633.sst
2015/12/31-16:01:47.812875 897 [env_flash] local file mismatch, expect 1104635, actual 0, delete /*****/00001633.sst
2015/12/31-16:01:47.814623 897 [env_flash] local env error, exit: /*****/00001633.sst
同时stderr中有
libsofa_pbrpc ERROR src/sofa/pbrpc/rpc_listener.h:187] on_accept(): accept error at 0.0.0.0:2002: Too many open files
libsofa_pbrpc ERROR src/sofa/pbrpc/rpc_listener.h:187] on_accept(): accept error at 0.0.0.0:2002: Too many open files
libsofa_pbrpc ERROR src/sofa/pbrpc/rpc_listener.h:187] on_accept(): accept error at 0.0.0.0:2002: Too many open files
libsofa_pbrpc ERROR src/sofa/pbrpc/rpc_listener.h:187] on_accept(): accept error at 0.0.0.0:2002: Too many open files
libsofa_pbrpc ERROR src/sofa/pbrpc/rpc_listener.h:187] on_accept(): accept error at 0.0.0.0:2002: Too many open files

怀疑可能是fd不够，可以和galaxy一起研究下怎么调整这些参数。

**Comment by 00k** [comment]
galaxy环境ulimit不足导致，已解决
