### ISSUE TITLE
负载均衡逻辑问题

### ISSUE THREAD

**Issue by bluebore** [baidu/tera#669]
迁移前
$ bin/teracli showts
     address status  workload  tablet  load  busy
  0  tera61  kReady  695.98M   2       0     0   
  1  tera62  kReady  32.06K    1       0     0   
  2 tera63  kReady  5.36G     1       0     0  
迁移后
$ bin/teracli showts
     address status  workload  tablet  load  busy
  0  tera61 kReady  752.27M   2       0     0   
  1 tera62 kReady  5.76G     2       0     0   
  2 tera63 kReady  0         0       0     0

**Comment by 00k** [comment]
长期未复现，暂且关闭
