### ISSUE TITLE
ts 退出，原因是与zk连接超时？

### ISSUE THREAD

**Issue by szxw** [baidu/tera#690]
E0109 00:00:10.698443   345 tabletnode_zk_adapter.cc:237] self node is deleted

W0109 00:00:10.698307   345 zk_adapter.cc:1166] zoo_exists fail : session expired
E0109 00:00:10.698443   345 tabletnode_zk_adapter.cc:237] self node is deleted

**Comment by xupeilin** [comment]
对，临时节点超时消失掉了
