### ISSUE TITLE
根据rowkey的前缀（或range）找到所有对应的tablet

### ISSUE THREAD

**Issue by taocp** [baidu/tera#736]
在实际中，需要这么一个功能，给定某个rowkey的前缀，例如 com.example.www（rowkey的前缀）， 要找出所有对应的tablet。
预期是 teracli 支持的功能，需要在某个范围内扫meta表。

有没有意见或者建议。。

**Comment by xupeilin** [comment]
当前findts只支持找第一个，你这里想找出所有的？

**Comment by taocp** [comment]
是的。

**Comment by 00k** [comment]
兹辞！
