### ISSUE TITLE
teracli无法正常显示version信息和help信息，在配置文件缺失的情况下。

### ISSUE THREAD

**Issue by xuxic** [baidu/tera#770]
我发现在配置文件缺失的情况下teracli会报错，并且./teracli version和./teracli help也都无法显示预期的内容，这个不太合理，因为version和help选项并不依赖配置文件。属于易用性问题，可以低优处理。使用场景是我在检查二进制程序的版本信息的时候通常不会特意先配好配置文件。

建议改成version和help信息的显示不依赖配置文件的存在。

复现方法是删掉tera.flag配置文件，然后直接运行teracli version和teracli help，命令就会报错，无法显示version或help信息。

**Comment by 00k** [comment]
已解决
