### ISSUE TITLE
用户反馈Tera同步读qps只有几十

### ISSUE THREAD

**Issue by bluebore** [baidu/tera#789]
人丢大了
@xupeilin @00k 
确认下是不是打包那个导致的，谁写的代码，谁去删吧。。。

**Comment by 00k** [comment]
write的打包是我写的，但我里面有发现sync=true时立即发的逻辑，后来其他人在仿照write写read的实现时漏了这个逻辑

**Comment by bluebore** [comment]
这个能否快速解决下？

**Comment by xupeilin** [comment]
@bluebore 最快的方法改个配置
`--tera_sdk_batch_size=1`

**Comment by 00k** [comment]
merge to #1044
