### ISSUE TITLE
应该能够追踪发起操作的用户ip等信息

### ISSUE THREAD

**Issue by taocp** [baidu/tera#841]
有个问题是，看到某个表有scan流量，大家（用户、Tera-DBA）都不知道到底谁在scan.

master端的meta操作应该每个都记录ip.

**Comment by bluebore** [comment]
master端记录并不解决问题吧
有人缓存了meta，可以永远用

**Comment by taocp** [comment]
我的意思是建表删表这种操作应该每次都记录ip，有人要造假那也没办法；

数据读写，ts也应该有机制告诉我们到底哪个ip在读、写、scan.

和缓存meta啥关系。。。没看懂。

**Comment by taocp** [comment]
已实现。
