### ISSUE TITLE
分裂写meta表顺序

### ISSUE THREAD

**Issue by yvxiang** [baidu/tera#874]
[这里](https://github.com/baidu/tera/blob/master/src/tabletnode/tabletnode_impl.cc#L966)分裂写meta表时，先写后半部分，再写前半部分，有什么深意吗？

**Comment by 00k** [comment]
目前来看没有任何深意，对于不会分裂的meta表来说，两半部分的修改是由同一个row_mutation提交到ts的，会保证原子性生效
