### ISSUE TITLE
tablet_task计数

### ISSUE THREAD

**Issue by lylei** [baidu/tera#947]
tablet_task当前使用局部计数器，导致写请求不会done run。改为一个全局计数器。

**Comment by xupeilin** [comment]
不会done run的原因是？

**Comment by lylei** [comment]
那个计数器记录的是一个tablet写的个数，然后调done run的条件是这个计数器和一个request的写个数相等。一个request里面如果写了多个tablet，两个值就永远不会相等了

**Comment by 00k** [comment]
done
