### ISSUE TITLE
SDK接口代码重整理

### ISSUE THREAD

**Issue by xupeilin** [baidu/tera#964]
[整理规则](https://github.com/baidu/tera/blob/master/doc/new_sdk_dev.md)
- [x] 独立include目录，分拆tera.h
- [x] 各类中接口分类排序，重写注释、文档
 - [x] error_code.h ErrorCode @xupeilin
 - [x] mutation.h RowMutation @xupeilin
 - [x] reader.h RowReader @xupeilin
 - [x] scan.h ScanDescriptor ResultStream @cjm
 - [x] table_descriptor.h ColumnFamilyDescriptor LocalityGroupDescriptor TableDescriptor @xupeilin
 - [x] table.h Table @xupeilin
 - [x] client.h Client @lylei

**Comment by taocp** [comment]
已完成
